<?php
// Demo content for Skill Map pages so the UI renders even before a real dataset is connected.

return [
    'auth' => [
        'admin@utm.my' => [
            'id' => 1,
            'name' => 'Dr. Lim Mei Yee',
            'email' => 'admin@utm.my',
            'password' => 'password',
            'role' => 'admin',
            'initials' => 'LMY',
        ],
        'student@utm.my' => [
            'id' => 2,
            'name' => 'Chong Pei',
            'email' => 'student@utm.my',
            'password' => 'password',
            'role' => 'student',
            'programme' => 'Information Systems',
            'year' => 'Year 4',
            'initials' => 'CP',
        ],
        'lecturer@utm.my' => [
            'id' => 3,
            'name' => 'Assoc. Prof. Aina Rahman',
            'email' => 'lecturer@utm.my',
            'password' => 'password',
            'role' => 'lecturer',
            'programme' => 'Information Systems',
            'year' => 'Staff',
            'initials' => 'AR',
        ],
        'staff@utm.my' => [
            'id' => 4,
            'name' => 'Ms. Farah Ismail',
            'email' => 'staff@utm.my',
            'password' => 'password',
            'role' => 'staff',
            'programme' => 'Information Systems',
            'year' => 'Staff',
            'initials' => 'FI',
        ],
    ],
    'student' => [
        'name' => 'Chong Pei',
        'programme' => 'Information Systems',
        'year' => 'Year 4',
        'institution' => 'UTM',
        'match_score' => 82,
        'skills_assessed' => 14,
        'skills_total' => 20,
        'badges_earned' => 3,
        'analyses_done' => 5,
        'last_analysis' => '5 Jul 2026',
        'recent_analyses' => [
            ['role' => 'Web Developer', 'score' => 82],
            ['role' => 'Data Analyst', 'score' => 77],
            ['role' => 'IT Support', 'score' => 69],
        ],
        'achievement_badges' => [
            ['name' => 'Bronze Explorer', 'date' => '10 May 2026', 'tier' => 'bronze'],
            ['name' => 'Skill Builder', 'date' => '28 May 2026', 'tier' => 'silver'],
            ['name' => 'Roadmap Runner', 'date' => '3 Jul 2026', 'tier' => 'gold'],
        ],
        'ai_insight' => 'Focus on API integration and deployment basics to raise your match score faster for web and product roles.',
        'profile_completion' => 76,
        'profile_categories' => [
            ['name' => 'Leadership', 'done' => true],
            ['name' => 'Technical', 'done' => true],
            ['name' => 'Interpersonal', 'done' => true],
            ['name' => 'Academic', 'done' => false],
            ['name' => 'Organisational', 'done' => false],
        ],
        'profile_skills' => [
            'Leadership' => [
                ['name' => 'Team Direction', 'description' => 'Sets priorities and keeps team members aligned.', 'score' => 4],
                ['name' => 'Decision Making', 'description' => 'Chooses practical options under time pressure.', 'score' => 3],
            ],
            'Technical' => [
                ['name' => 'PHP', 'description' => 'Server-side scripting and backend logic.', 'score' => 4],
                ['name' => 'MySQL', 'description' => 'Querying and schema design for relational data.', 'score' => 4],
                ['name' => 'JavaScript', 'description' => 'Client-side interactivity and fetch-based workflows.', 'score' => 3],
            ],
            'Interpersonal' => [
                ['name' => 'Communication', 'description' => 'Clear updates with teammates and supervisors.', 'score' => 4],
                ['name' => 'Collaboration', 'description' => 'Works effectively in project teams.', 'score' => 4],
            ],
            'Academic' => [
                ['name' => 'Research Writing', 'description' => 'Turning findings into structured documentation.', 'score' => 3],
            ],
            'Organisational' => [
                ['name' => 'Planning', 'description' => 'Breaks work into manageable steps.', 'score' => 3],
            ],
        ],
        'analyse_roles' => [
            ['name' => 'Web Developer', 'icon' => 'bi-code-slash', 'tags' => ['PHP', 'MySQL', 'JavaScript', 'Bootstrap', 'Git'], 'mapped' => 18],
            ['name' => 'Data Analyst', 'icon' => 'bi-bar-chart-line', 'tags' => ['SQL', 'Excel', 'Python', 'Tableau', 'Statistics'], 'mapped' => 16],
            ['name' => 'IT Support', 'icon' => 'bi-pc-display', 'tags' => ['Troubleshooting', 'Windows', 'Networking', 'Ticketing'], 'mapped' => 12],
            ['name' => 'Network Engineer', 'icon' => 'bi-diagram-3', 'tags' => ['TCP/IP', 'Routing', 'Switching', 'Security'], 'mapped' => 14],
            ['name' => 'Cybersecurity Analyst', 'icon' => 'bi-shield-lock', 'tags' => ['Threats', 'Linux', 'SIEM', 'Risk'], 'mapped' => 13],
        ],
        'leadership_roles' => [
            ['name' => 'Student Club President', 'icon' => 'bi-people-fill', 'tags' => ['Leadership', 'Public Speaking', 'Event Planning'], 'mapped' => 11],
            ['name' => 'Academic Project Manager', 'icon' => 'bi-kanban-fill', 'tags' => ['Planning', 'Coordination', 'Reporting'], 'mapped' => 10],
            ['name' => 'Peer Mentor Lead', 'icon' => 'bi-mortarboard-fill', 'tags' => ['Mentoring', 'Empathy', 'Coaching'], 'mapped' => 9],
        ],
        'gap_analysis' => [
            'role' => 'Web Developer',
            'match' => 82,
            'status' => 'Good Match',
            'summary' => ['have' => 8, 'partial' => 4, 'missing' => 2],
            'verdict' => 'You are close to job-ready for this target role.',
            'focus' => 'Strengthen API Integration, responsive layout testing, and deployment workflow.',
            'eta' => '4 to 6 weeks',
            'skills' => [
                ['skill' => 'PHP', 'category' => 'Technical', 'rating' => 4, 'required' => 4, 'status' => 'Have', 'gap' => 0],
                ['skill' => 'MySQL', 'category' => 'Technical', 'rating' => 4, 'required' => 4, 'status' => 'Have', 'gap' => 0],
                ['skill' => 'Bootstrap 5', 'category' => 'Technical', 'rating' => 3, 'required' => 4, 'status' => 'Partial', 'gap' => 1],
                ['skill' => 'JavaScript', 'category' => 'Technical', 'rating' => 3, 'required' => 4, 'status' => 'Partial', 'gap' => 1],
                ['skill' => 'API Integration', 'category' => 'Technical', 'rating' => 2, 'required' => 4, 'status' => 'Missing', 'gap' => 2],
            ],
        ],
        'roadmap' => [
            'role' => 'Web Developer',
            'match' => 82,
            'complete' => 64,
            'summary' => ['missing' => 2, 'partial' => 3, 'completed' => 7],
            'hours' => 42,
            'days' => 18,
            'missing' => [
                ['skill' => 'API Integration', 'platform' => 'Coursera', 'duration' => '6 hours', 'free' => true, 'progress' => 0, 'resource' => 'Build a REST API with PHP'],
                ['skill' => 'Deployment Basics', 'platform' => 'YouTube', 'duration' => '3 hours', 'free' => true, 'progress' => 15, 'resource' => 'Deploy to Apache and cPanel'],
            ],
            'partial' => [
                ['skill' => 'Bootstrap 5', 'platform' => 'Udemy', 'duration' => '5 hours', 'free' => false, 'progress' => 60, 'resource' => 'Responsive UI build-up'],
                ['skill' => 'JavaScript', 'platform' => 'MDN', 'duration' => '4 hours', 'free' => true, 'progress' => 55, 'resource' => 'Fetch and async patterns'],
                ['skill' => 'Git', 'platform' => 'Atlassian', 'duration' => '2 hours', 'free' => true, 'progress' => 75, 'resource' => 'Branching and collaboration'],
            ],
            'completed' => [
                ['skill' => 'PHP', 'platform' => 'Codecademy', 'duration' => '8 hours', 'progress' => 100, 'resource' => 'Server-side fundamentals'],
                ['skill' => 'MySQL', 'platform' => 'W3Schools', 'duration' => '7 hours', 'progress' => 100, 'resource' => 'Queries, joins and schema design'],
            ],
        ],
        'progress' => [
            'delta_month' => 9,
            'skills_improved' => [
                ['name' => 'JavaScript', 'delta' => '+1'],
                ['name' => 'Bootstrap 5', 'delta' => '+1'],
                ['name' => 'API Integration', 'delta' => '+2'],
            ],
            'streak' => 12,
            'badges' => [
                ['name' => 'Bronze Explorer', 'progress' => 100, 'unlocked' => true],
                ['name' => 'Skill Builder', 'progress' => 100, 'unlocked' => true],
                ['name' => 'Roadmap Runner', 'progress' => 100, 'unlocked' => true],
                ['name' => 'Career Ready', 'progress' => 70, 'unlocked' => false],
            ],
            'history' => [
                ['date' => '12 Jun 2026', 'role' => 'Web Developer', 'score' => 73, 'change' => '+5'],
                ['date' => '24 Jun 2026', 'role' => 'Data Analyst', 'score' => 77, 'change' => '+4'],
                ['date' => '5 Jul 2026', 'role' => 'Web Developer', 'score' => 82, 'change' => '+5'],
            ],
        ],
        'report' => [
            'generated' => '5 Jul 2026',
            'pages' => 8,
            'share_link' => 'https://skillmap.local/share/utm-cp-2026',
            'match' => 82,
            'top_missing' => [
                ['skill' => 'API Integration', 'resource' => 'Build a REST API with PHP', 'platform' => 'Coursera'],
                ['skill' => 'Deployment Basics', 'resource' => 'Deploy to Apache and cPanel', 'platform' => 'YouTube'],
                ['skill' => 'Test Automation', 'resource' => 'Introduction to testing workflows', 'platform' => 'freeCodeCamp'],
            ],
        ],
    ],
    'admin' => [
        'analytics' => [
            'month' => 'July 2026',
            'total_students' => 248,
            'new_students' => 34,
            'avg_match' => 74,
            'avg_change' => '+6%',
            'popular_role' => 'Web Developer',
            'missing_skill' => 'API Integration',
            'missing_skill_pct' => 41,
            'missing_skills' => [
                ['name' => 'API Integration', 'pct' => 41],
                ['name' => 'Deployment', 'pct' => 38],
                ['name' => 'Leadership Communication', 'pct' => 34],
                ['name' => 'Testing', 'pct' => 31],
                ['name' => 'Report Writing', 'pct' => 28],
                ['name' => 'Version Control', 'pct' => 24],
                ['name' => 'Data Visualisation', 'pct' => 21],
                ['name' => 'Documentation', 'pct' => 19],
            ],
            'programmes' => ['Information Systems', 'Software Engineering', 'Computer Science'],
        ],
        'categories' => [
            ['name' => 'Technical', 'type' => 'Skill Category', 'subcategories' => 6, 'updated' => '2 Jul 2026', 'icon' => 'bi-code-square'],
            ['name' => 'Leadership', 'type' => 'Skill Category', 'subcategories' => 4, 'updated' => '1 Jul 2026', 'icon' => 'bi-people-fill'],
            ['name' => 'Interpersonal', 'type' => 'Skill Category', 'subcategories' => 5, 'updated' => '29 Jun 2026', 'icon' => 'bi-chat-dots-fill'],
            ['name' => 'Academic', 'type' => 'Skill Category', 'subcategories' => 4, 'updated' => '26 Jun 2026', 'icon' => 'bi-journal-text'],
            ['name' => 'Organisational', 'type' => 'Skill Category', 'subcategories' => 3, 'updated' => '20 Jun 2026', 'icon' => 'bi-folder-check'],
            ['name' => 'Web Developer', 'type' => 'Target Role', 'subcategories' => 12, 'updated' => '4 Jul 2026', 'icon' => 'bi-code-slash'],
        ],
        'skills' => [
            ['name' => 'PHP', 'category' => 'Technical', 'description' => 'Server-side scripting for backend logic.', 'difficulty' => 3, 'roles' => ['Web Developer', 'IT Support'], 'status' => 'Active'],
            ['name' => 'MySQL', 'category' => 'Technical', 'description' => 'Structured querying and relational database design.', 'difficulty' => 3, 'roles' => ['Web Developer', 'Data Analyst'], 'status' => 'Active'],
            ['name' => 'JavaScript', 'category' => 'Technical', 'description' => 'Interactive client-side application behaviour.', 'difficulty' => 3, 'roles' => ['Web Developer', 'Cybersecurity Analyst'], 'status' => 'Active'],
            ['name' => 'Bootstrap 5', 'category' => 'Technical', 'description' => 'Responsive layout and UI components.', 'difficulty' => 2, 'roles' => ['Web Developer'], 'status' => 'Active'],
            ['name' => 'Git', 'category' => 'Technical', 'description' => 'Version control and collaboration workflow.', 'difficulty' => 2, 'roles' => ['Web Developer', 'Academic Project Manager'], 'status' => 'Active'],
        ],
        'benchmarks' => [
            'roles' => [
                ['name' => 'Web Developer', 'type' => 'Career', 'skills' => 12, 'avg_required' => 4.1, 'critical' => 5, 'updated' => '4 Jul 2026'],
                ['name' => 'Data Analyst', 'type' => 'Career', 'skills' => 11, 'avg_required' => 3.9, 'critical' => 4, 'updated' => '3 Jul 2026'],
                ['name' => 'Student Club President', 'type' => 'Lead', 'skills' => 9, 'avg_required' => 3.7, 'critical' => 3, 'updated' => '30 Jun 2026'],
            ],
            'selected' => 'Web Developer',
            'selected_skills' => [
                ['name' => 'PHP', 'category' => 'Technical', 'required' => 5, 'priority' => 'Critical'],
                ['name' => 'MySQL', 'category' => 'Technical', 'required' => 4, 'priority' => 'Critical'],
                ['name' => 'Bootstrap 5', 'category' => 'Technical', 'required' => 4, 'priority' => 'Important'],
                ['name' => 'JavaScript', 'category' => 'Technical', 'required' => 4, 'priority' => 'Critical'],
                ['name' => 'Git', 'category' => 'Technical', 'required' => 3, 'priority' => 'Important'],
            ],
        ],
        'users' => [
            ['name' => 'Chong Pei', 'email' => 'student@utm.my', 'programme' => 'Information Systems', 'year' => 'Year 4', 'analyses' => 5, 'best_match' => 82, 'top_role' => 'Web Developer', 'streak' => 12, 'last_active' => '5 Jul 2026', 'status' => 'Active'],
            ['name' => 'Nur Ainaa', 'email' => 'aina@utm.my', 'programme' => 'Information Systems', 'year' => 'Year 3', 'analyses' => 4, 'best_match' => 77, 'top_role' => 'Data Analyst', 'streak' => 8, 'last_active' => '4 Jul 2026', 'status' => 'Active'],
            ['name' => 'Syafiq Hassan', 'email' => 'syafiq@utm.my', 'programme' => 'Computer Science', 'year' => 'Year 4', 'analyses' => 2, 'best_match' => 68, 'top_role' => 'IT Support', 'streak' => 3, 'last_active' => '30 Jun 2026', 'status' => 'Inactive'],
        ],
    ],
];
